### ISSUE TITLE
post process warnings

### ISSUE THREAD

**Issue by latimeria68** [SpoddyCoder/clonepi#2] opened 2018-11-01 21:52 UTC
hello,
please see below, are those warnings something I should worry about?
thanks

- User confirmed, starting clone process : 2018-11-01T22:46:34
Info: setting up source directories and mounts...
Info: setting up destination directories and mounts...
Info: created clone partition dir at /mnt/clone/sda2
Info: mounted /dev/sda2 to /mnt/clone/sda2
Info: mounted /dev/sda1 to /mnt/clone/sda1
Info: starting filesystem sync processes, this may take some time...
Info: syncing: /  -->  /mnt/clone/sda2
Info: this is the running root directory, applying OS excludes
Info: rsync --force --delete -rltgopxWDE --exclude=/mnt/source --exclude=/mnt/clone --exclude-from=/etc/clonepi/raspbian.excludes / /mnt/clone/sda2/
Info: syncing: /boot  -->  /mnt/clone/sda1
Info: rsync --force --delete -rltgopxWDE /boot/ /mnt/clone/sda1/
Info: ...all sync processes finished OK
Info: total clone process time : 1m 0s
Info: cleaning up...
Info: unmounted destination partition from /mnt/clone/sda2
Info: deleted empty destination partition dir /mnt/clone/sda2
Info: unmounted destination partition from /mnt/clone/sda1
rmdir: failed to remove '/mnt/clone/sda1': Directory not empty
Warning: could not delete destination partition dir /mnt/clone/sda1, perhaps it's not empty?
rmdir: failed to remove '/mnt/clone': Directory not empty
Warning: could not remove clone dir /mnt/clone, perhaps it's not empty?
ClonePi finished succesfully but with WARNINGS : 2018-11-01T22:47:35

**Comment by PushEngineering** [comment] 2018-11-01 22:31
Probably not anything to worry about. But you should check the directories that have the warnings. Can you run the following 2 commands and let us know the results;

```
sudo ls -al /mnt/clone/
sudo ls -al /mnt/clone/sda1/
```

**Comment by latimeria68** [comment] 2018-11-01 22:55
- $ sudo ls -al /mnt/clone/
total 16
drwxr-xr-x  4 root root 4096 Nov  1 23:33 .
drwxr-xr-x  3 root root 4096 Nov  1 19:04 ..
drwxr-xr-x  4 root root 4096 Jan  1  1970 sda1
drwxr-xr-x 22 root root 4096 Nov  1 18:45 sda2
$ sudo ls -al /mnt/clone/sda1/
total 22152
drwxr-xr-x 4 root root    4096 Jan  1  1970 .
drwxr-xr-x 4 root root    4096 Nov  1 23:33 ..
-rwxr-xr-x 1 root root   23315 Sep 19 19:06 bcm2708-rpi-0-w.dtb
-rwxr-xr-x 1 root root   22812 Sep 19 19:06 bcm2708-rpi-b.dtb
-rwxr-xr-x 1 root root   23071 Sep 19 19:06 bcm2708-rpi-b-plus.dtb
-rwxr-xr-x 1 root root   22589 Sep 19 19:06 bcm2708-rpi-cm.dtb
-rwxr-xr-x 1 root root   24115 Sep 19 19:06 bcm2709-rpi-2-b.dtb
-rwxr-xr-x 1 root root   25311 Sep 19 19:06 bcm2710-rpi-3-b.dtb
-rwxr-xr-x 1 root root   25574 Sep 19 19:06 bcm2710-rpi-3-b-plus.dtb
-rwxr-xr-x 1 root root   24087 Sep 19 19:06 bcm2710-rpi-cm3.dtb
-rwxr-xr-x 1 root root   52116 Sep 25 10:06 bootcode.bin
-rwxr-xr-x 1 root root     143 Jan  1  1980 cmdline.txt
-rwxr-xr-x 1 root root    1589 Nov  1 17:45 config.txt
-rwxr-xr-x 1 root root   18693 Mar  9  2018 COPYING.linux
-rwxr-xr-x 1 root root    2618 Sep 25 10:06 fixup_cd.dat
-rwxr-xr-x 1 root root    6660 Sep 25 10:06 fixup.dat
-rwxr-xr-x 1 root root    9893 Sep 25 10:06 fixup_db.dat
-rwxr-xr-x 1 root root    9889 Sep 25 10:06 fixup_x.dat
-rwxr-xr-x 1 root root     145 Oct  9 13:33 issue.txt
-rwxr-xr-x 1 root root 4935528 Sep 25 10:06 kernel7.img
-rwxr-xr-x 1 root root 4685760 Sep 25 10:06 kernel.img
-rwxr-xr-x 1 root root    1494 Mar  9  2018 LICENCE.broadcom
-rwxr-xr-x 1 root root   18974 Oct  9 13:33 LICENSE.oracle
drwxr-xr-x 2 root root    4096 Oct  9 12:50 overlays
-rwxr-xr-x 1 root root  677764 Sep 25 10:06 start_cd.elf
-rwxr-xr-x 1 root root 5108996 Sep 25 10:06 start_db.elf
-rwxr-xr-x 1 root root 2847044 Sep 25 10:06 start.elf
-rwxr-xr-x 1 root root 4047876 Sep 25 10:06 start_x.elf
drwxr-xr-x 2 root root    4096 Nov  1 17:43 System Volume Information

**Comment by latimeria68** [comment] 2018-11-01 22:58
other strange behaviour is that the second time you make  a clone and an incremental backup is expected I got this error with mtab:

- $ sudo clonepi /dev/sda --ignore-warnings

grep: /etc/mtab: No such file or directory
Warning: /mnt/clone/ is not empty - contents could be erased if you choose to continue.
grep: /etc/mtab: No such file or directory
cat: /etc/mtab: No such file or directory

**Comment by SpoddyCoder** [comment] 2018-11-01 23:47
It looks like it was unable to unmount the temporarily created clone dirs. Please run the following...

```
sudo umount /mnt/clone/sda1
sudo umount /mnt/clone/sda2
```

Then list the directory contents after...

```
sudo ls -al /mnt/clone/sda1
sudo ls -al /mnt/clone/sda2
```

... if both of these listings show empty, you can then safely remove the clone dir...

```
sudo rm -rf /mnt/clone
```

I would not suggest using `--ignore-warnings` until you have clonepi running properly as the warnings help you diagnose issues.

The warning on the 2nd run is a product of the error from the first run - you still have the old `/mnt/clone` directories in place  - clonepi will not overwrite them by default - as they could still have your system mounted and bad things can occur.

Not sure why you don't have an `/etc/mtab` file - this is a basic file that linux OS's require to run properly - it's the OS way of keeping track of currently mounted directories - clonepi queries this to understand current state. It's likely the root cause of your issues.

**Comment by latimeria68** [comment] 2018-11-02 10:20
well, I think all problems are coming from usb disks automounted through udisk2/udiskie: I'm looking for a way to backup my running Nextcloudpi microSD....I will check if there'a a way to prevent my backup microSD to be involved in the logics of udisk2/udiskie
thanks for your comment

> https://github.com/nextcloud/nextcloudpi/blob/master/etc/ncp-config.d/nc-automount.sh

**Comment by SpoddyCoder** [comment] 2018-11-02 10:44
Oh I see - I'm not familiar with udiskie, but will take a look at how it operates and see if clonepi needs to be a bit more defensive / pro-active when it's in use.

If you can keep us updated on your investigations too, that'd be useful.

NextCloudPi looks interesting - I'll be checking it out :)

**Comment by latimeria68** [comment] 2018-11-10 17:45
it was finally quite simple to avoid all conflicts between udisk2/udiskie (when you have nc.automount active inside your NexctloudPi instance) and mount/umount commands inside the clonepi:
`sudo systemctl stop udisks2.service`
before you run the clonepi process, and then:
`sudo systemctl start udisks2.service`
after clonepi has finished.
Up to now tested twice and all seems to sounds good; the "cloned" microSD boots without problems.
Even more simple is to clonepi to an img file as this does not conflict at all with udisks2 service.
Thank you for this great tool

**Comment by SpoddyCoder** [comment] 2018-11-11 21:51
Thanks for updating the issue thread. The script hooks can be used for this also - README has more detail.

As stopping/starting services is the most common use case for the script hooks - a future update will introduce a dedicated switch to make it even easier. Will likely look like this...

```
sudo clonepi /dev/sdb --systemctl-services="udisks2"
```

This will stop the service(s) prior to clone start & start them after finishing (CSV list of systemctl managed services). I'll close this issue when it's released - so you'll get a notification when it's available.

**Comment by SpoddyCoder** [comment] 2018-11-24 23:25
@sgiannulli ClonePi v1.7.1 has just been released with the new `--services` feature, documented in the README. I've also included a check for the udisks2 service in the pre-flight checks, as it's known to cause issues. If ClonePi detects it's running it will output a warning...

```
sudo ./clonepi /mnt/nas-pi-bak/system-backups/pi-ex-test.img

Warning: udisks2 service is running, consider using the --services switch to stop/start it, check README for more info
Error: not continuing, check warning and re-run ClonePi. Use --ignore-warnings to suppress this error.
Aborting!
```

Use the new switch to get ClonePi to automatically stop/start the udisks2 service & remove the warning...

```
sudo ./clonepi /mnt/nas-pi-bak/system-backups/pi-ex-test.img --services=udisks2

Info: destination file /mnt/nas-pi-bak/system-backups/pi-ex-test.img exists and will be updated
Info: new loop device created for the clone : /dev/loop0
Pre-flight checks completed OK
Info: the following actions will be taken...
Info: 1) destination disk partitions will be mounted inside /mnt/clone/:
Info:    /dev/loop0p2
Info:    /dev/loop0p1
Info: 2) udisks2 service(s) will be stopped
Info: 3) filesystems will be synced:
Info:    /  -->  /mnt/clone/loop0p2
Info:    /boot  -->  /mnt/clone/loop0p1
Info: 4) udisks2 service(s) will be restarted
Info: 5) cleanup source + destination mounts & dirs
```

Hope you find it useful :)

**Closed as completed** 2018-11-25 17:09 UTC

**Comment by latimeria68** [comment] 2018-11-25 18:00
tested and working
thank you
